version: '3.9'

networks:
  rinha:
    driver: bridge
  
services:

  mongodb:
    container_name: DB
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=senha!123
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rinha
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "330MB"
  
  api01: &api
    container_name: API01
    image: vctrmglhs/rinha-backend-fastapi:latest
    depends_on:
      - mongodb
    environment:
      - mongodb_uri=mongodb://user:senha!123@mongodb:27017/admin
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "100MB"

  api02:
    <<: *api
    container_name: API02

  nginx:
    container_name: LB
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - rinha
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"